apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: staging
spec:
  encryptedData:
    token: AgAZansq8I4kDRgeGji4RnS+IQZc0ODsKNsdT1i2Zmidco1jA8nfu4xIwZQMPTy43mAi9WuDnkvWZct70AHK78pW9nOHm6afv0UhkXQ3T7pTk1rQdCxik5l/Pv7/t3gVf7h/9/cO+0qbpOlkDHl1GN2dli87pu7gTVfc0GMvQhguW65chLUDFOnQW7SjimnFYkNhQNjDO64H6OKvjJNW19GFsCVUbd1KRZvpq1vDIov5TtgpXTjBFLJXz8OQmZAhiOwk3RFqjSYK/TLAl5NVgwhQ1KzlKJ1kbIO9K/JovIFKW8pYiObtWvkhFiF58vVZczUNklow2vR4+MlvFsoGigISGmjnR7QvnhR0i1RL36rkfMe+WMjY6n1anMhge/2VNHMIxLw4KTcmcW4emkcH4VtMqEIruUQMFNcoJQEPnlLt19FllizqaXpEvDcBrUFEp4cMzc8FQwBli2OWnSEFWZPJav7nPMUbmkv2hy4apC4U5u7BikQ0o+9pDjqJ2IRpMN1OxqdBrmzFQFmIcwsMNTJbgfwp4gGN1Hiv2LfCLSDlNosg7UhTT50ZI5HC8mGnqJFRtCHr/q3qQTBxs5MFiFw2xF+ImqBu+Re6mIQPR2nMzZuHGLEbRpvvlztTcK2CkcVq04+yF2Tk8BcT8iBnbAH0J5Rnj0ZvpaxFPihldOX6h7GSxLDnKF/7eulB1bhthWLch/OMiCgmA1iZXR15LsFIsnKgIbeQ1Nccq9iVzxCe5QzzwC2j3QBObMxJ4w18SBLnrkUd6j63YvCqOMsUlFsrablysuwGwiwAMKNE
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: staging
    type: Opaque
status: {}

