apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: website-staging
  namespace: staging
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: website-staging
  chart:
    git: git@github.com:cloud-native-nordics/k8s-config-repo
    path: charts/cloud-native-nordics-default
    ref: master
  values:
    replicaCount: 1
    image:
      repository: cloudnativenordics/website
      tag: 1.0.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
    fullnameOverride: "website"
    nameOverride: "website"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      path: /
      hosts:
      - staging.cloudnativenordics.com
      tls:
      - secretName: website
        hosts:
          - staging.cloudnativenordics.com