apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: production
spec:
  encryptedData:
    token: AgC1Y3eCTjERcpgqNnb83rkqNAhqELriHgTQ2sE7+ct6wXJzUMzKyEKLOJoav5/IBH2ba0s/gZXgVLoc8s06hQy/J/gh5wCgukiRnAfcGo59WzaIemj/tn/OiIxc1nXXGrvuCjsSfaxKLL4WfCqPbC6qx8bN0RdICuVWagNoKRkpSLH2GHEB1s47CK+NmTRazzUtS/u97OQVSRd+N4uWFQu3H1zv99vmyYQpcYDthOXCJtPk/eHPRD0Tv/XCYkA1AHCly4tEAOKNwyXC2apN7stJBsbUma/yIiMkuiHmJrQYr+U4RykQZBujlfVfaLz23XZqvXfno39sEXGpvH7yPFyT2wRUpcBOO4VRqVOfPCYUdb41PBEnpPDEuIbuOFz3tTD6fBgkvc4looWd29fT1yAAxxq3ypHHBBDcYi33HL5MxrO2PMPL4v4dZ8/lPQGz+KLDrLts855cODT/b84oJL+HqSK8ZDp4WNES+e6YdZkNRc2wUNaMOgm35V1ZlsHD696dzQZ68WpYBd1fAltKXGPQI4ppnGwSfsXhb3V8y2p0Zx63yJH3ALcdi6k3xakSCA/YrHSPtqJ+JIrO3IsRMIbuoVeN9xEmL1rZY3H57SfTi/EC10Z7Bh0ukj1q56601UHcs0l7xKdz44cWwOjbZ2Eu4OWceu/neQjHcVHTwOEJaulN4WgdDEKNCjT77EdO2d/byJBb2aNZciIAFQEh+Bl3MMZqi0YRB1171dATwNyHn0v8WZ2fhuMXv+fZ9Nqt9lPawn31nAWmKavH3dJrX8CnysypsN7XQSad4V3h
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: production
    type: Opaque
status: {}

