apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: default
spec:
  encryptedData:
    token: AgA01mvO001AM6PbZEoYOUq8l9ikuHeqRPvoRv3Yw796mBbpFsdBOY+BEnEv2gTRmOmPoubOgyXuJwz2Y2nRwxhWYhtiywkzSFotK7vE5IGqmuYQWPx1Sk1KQymrtjriPf/KpQOhjnsel7KmtfRj5oCX1GNgUkEkaCqqDc5VI5eR2cqIfrqEra6aQczDWY1rflwUc2cuc6X1ZzHOrEfDHHoW9+riRQwivQSNs6ASZ6TGq7poMaPEZxrZfRDTQemNO6UD34o8JomDkedVTgoJbd1a8aYYu6BbGep+8jelBeTD4VpcZ2ac6tlbeMvmk3Su1g5e5olYROAN86Y4k6xb7Nx9hmZWSWSQH+EzG2/GKDPn/g35Jc6rPcpFST2I+c9rKnv7Q6FGEQsjGs+fbYmKCuGydJuBaZfjVirY1mzSwDkA+JCaSjkq41bzg9dm9qXgXuV99/ZyxJdZxOmx6O2/6wh94J/XFe+IUaFSMKgRbzcRHXNhPTiRsatVFk1nCZa8s9b1kSc5wI4cHNCPfwLV/MeXa1df7LO16w8l4oV0Wr/gFLnJcHpYNoMubc7Zbe0c6nAWEbRZG60dwSAjv2Qir0HkC3azHiToStFVw1mkiK5gNGs6FZ9UdBR3G2emjaDv4HZhwBry1i1eH2Wuvsm3nnBpev+1Aok3fPTGT4xMVYv2ogAW3eQT2hDidQclPI02nbWwsMSdkrH47q/5ZE309Jkn/C+dysHM03GDpRLLFKiKn0z1ZT4da/iDtfy/IIwNBZLGCN8nCy69CLhcA6XUiEXyDU/4TfupdOQSfX4H
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: default
    type: Opaque
status: {}

