apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: default
spec:
  encryptedData:
    token: AgBNoNLtRuZko961F+m32nlNh7LqIsU4H68Ja+egWM8vz6A3bPrJgjWyitvi7SwABS+8bANEaJFf7qtYG0VwO06aXwlF6sgqrkNdLZhUpdyShIqNi2CI+bj2vdY1WdjXR9c++aOvXaxJWCtowogJRxwIV1TjQ5eH4eZ1XY4vstC233z8RSgMRM5prFJ/6BY4v4Mqyd8YB8bmWNVLvpFeST888Wrsp8oO4KH1N/etj6D1rLUblnVm3gMalf7MiOEOCso3OZEAuFU5uVfuqEuWlSsioEbHF6xq2AHWr5cm/vA1UsUR/Rm4kPs2aJyY9Tz8/pfP4hxA3S6Y/w2t6GV9dYjuK7/ruz2irJj+GMgUmL+rruytZdwhxf4JbeRQldPxYDuZEplCnLR3blzMNEmZKrhEsYgb7vN1EmDeO4LKK6VE+x7F4CCU3pssWgcda/9fXOBYzSMOlTj2Msp6LGkwc/5RAlCUnrHznuj6LguzM15MX4Pfu4n92ySaIx4L99r4eA3OBXrechPOcla7SoGSaZbeRb11FlaNWhdeGQDVv+egTXLcOXbp88Zg9PjJLVebylmmw1NNazw7y6K48qXc7dJA/4HTY1izJe0DJoPrFY9/KVPfpwWKu94Jt/i9Aesz0JDaHTl02uV0iv+DqHQVixr+Q1gSYUnLC/HVid9RceyBd/BjCvvtwDtRz8y7I0iDnNleSsF1zx9/y8k8l6DUWCMJ506nQxEsohmyUKTFGDtaAK6GtmeAqHnR7IbEV1t9l4vq527pkQZ3r4GlRejzdYeXZortk3bZiRH5QUFa
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: default
    type: Opaque
status: {}

