apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: default
spec:
  encryptedData:
    admin-password: AgDKbxyBXD43S+ltY6l8eqjeHLNetQtECGNXlAHvcbJ6cywwFzFWYnIki0VGf/Jpm9Q9VY5LReGn9FWktM0NkhBn2GdgTgy6xREvR7xKDzm/IsQolJfUy8f5GigKWBRT1VKAtPLTSZ5KHSkK6GBbkql3z77yMSLQulB7Tx3Umz2HS39NKXqtSFtfoCf453V4L8sBkhwmAcfzHNvx8yr3OaPnn7EhRJtjKfQGdw59rvtx3rDcrumJE+MAhvnaM6lZP2p5XC2Acd+Z7r5lkJ39dqYN5oq2TLKBkvQQER8LOuYGD5ZnTcNs+H1gcva0I5EC3tMfXXJwiqp7Lf5YHpAgI+kHl/iEIcgivSDX3DvMJSZDZID7IdDJn0dRC9Hiqb+LvbOlnAIQMXSKjMvq6UvI2WnANltqm+UEU0rgX1XoEpog53WBSbkJG+6PTpXzT/Ov5lRM8e/O7hB812i3kqqeZMAqLfYiY6b6yqhyro+HURQqjScAvI3aNb1CXUvMFvuGv8B5uBNxT61mrzQo1EowxXfiVOy82TVYnFFd/55x+V/Lz70nFqtnAfLIiVeB/8cKVLa9diSIUHAUHK/Xezr78iTXowUvWaciNJ9panGLRERGnaE40XTFMmQC4+XAMZumpq4JWd1VZyOtoqWrZdSFe/LRnoCZn9M3U1CMWVNcxm9I/IGKczi6r+SQnOoGckLfwsoPbGiXSBnNRmk8QsaxQ6FF3pn+gRygtR/uWDkHOqr0zQ==
    admin-user: AgBUcnoO0QefL7KxLx9ZKqPtw6hMun2Lj5gPj+isXxkxfjMkVRVYY3QpFeYxIBQr8RdlcxxIlabhe/brHS+s3LjOdBaZBBXN9Te1cYI2zTH+Smc03KwNm3f/c/+DUxFu25PfsAklxajMrCi/RtJo0GDJ+agWiQ4UjdPMn3CgZu7DBdsGqTVSANvToProbCsVSEHqH8pS9+vRvbbeAgs+BHFT2HiuFSsys3NyujX1olak9/qSrinfzwRccTQ8QSdodCDXbwWzJNMA6JayKfoiktaJHQkILv2uiyfYfG5HwRFGdPTycfWpsFMg2BBvss9xArFGET22cmLZseWvcKybRAUqRvmbsSEmI+oWUvXDklocLxKDoRn1rKoAi4jZBGQUMyvrxzjKdJ+evHYnTaclfdijqMISlaM3ToDglPYjZ0yQjnZ2vnyxDPekt5PsbqnwUIvta/quINma8kz6noCDJsTWQQvh/EzyH7sWx1/uu43WtFA+iPIJCjGNWWQLBGoRF/AAwXEt+QhCSEhkfmjieRUnaJcPhonyPLWGs5OdDCH5ah9sekk8r0PNGocmkzNFfsiBwATHPicQVhnAmNQ0PFlOxrz6O1XOd6+0jVk5CP3bJjjgviJaXAqmqLyTqswWEyo2GdI6bpKPBpiTzazJ38tubvbCpMJ1P/oVsf2BMTyKyIwDcK3x75qrhwz8w2px7XGc+yW/nkx57OrcS4e5bdYgQzw=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: default
    type: Opaque
status: {}

