apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stats-api
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: stats-api
  chart:
    git: git@github.com:cloud-native-nordics/k8s-config-repo
    path: charts/cloud-native-nordics-default
    ref: master
  values:
    replicaCount: 1
    image:
      repository: cloudnativenordics/stats-api
      tag: 1.0.1
    service:
      type: ClusterIP
      port: 8080
    fullnameOverride: "stats-api"
    nameOverride: "stats-api"
    ingress:
      enabled: true
      path: /
      hosts:
      - stats-api.cloudnativenordics.com
      tls:
      - secretName: stats-api
        hosts:
        - stats-api.cloudnativenordics.com
      command:
        - ./app
        - --v=5
        - --logtostderr=true
        - --slack-token=$(SLACK_TOKEN)
      env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: token