---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: website
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: website
  chart:
    git: git@github.com:cloud-native-nordics/k8s-config-repo
    path: charts/cloud-native-nordics-default
    ref: master
  values:
    replicaCount: 1
    image:
      repository: cloudnativenordics/website
      tag: master-5529f64
    service:
      type: ClusterIP
      port: 80
    fullnameOverride: "website"
    nameOverride: "website"
    ingress:
      enabled: true
      path: /
      hosts:
      - v2.cloudnativenordics.com
      tls:
      - secretName: website
        hosts:
        - v2.cloudnativenordics.com
